---
- hosts: devserver
  become: yes
  ignore_errors: yes
  vars: 
    pkg_name: httpd
    username: fetchina
  tasks:
    - name: creating user 
      user: 
        name: "{{ username }}"
        comment: fetchina admin
        shell: /bin/bash
          # when:  ansible_os_family == "Debian" 
    - name: create file 
      file: 
        path: /tmp/ansible.txt
        state: touch
         #group: foo
         #owner: fet
        mode: '0600'
      register: output
    - name: read the output
      debug: 
       msg: "hello from ansible this is running  on {{ ansible_os_family }}"
    - name: create directory 
      file:
        path: /tmp/dir
        state: directory
        mode: '0777'
      tags:
        - app1
        - c1
    - name: create a file
      shell: cat /etc/passwd | grep fetchina    
    - name: install apache
      yum:
        name: "{{ pkg_name }}"
        state: present 

    - name: install finger
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - finger 
          
    


